version: '3'
services:
  app:
    build:
      context: ./docker/app
    volumes:
      - ./:/go/src/go-vue-sns
    ports:
      - "8083:8083"
    env_file: .envapp
    depends_on:
      - db

  db:
    build:
      context: ./docker/db
    ports:
      - "3306:3306"
    env_file: .envdb
    volumes:
      - go-vue-sns:/var/lib/mysql

volumes:
  go-vue-sns:
    driver: local
